---
script: "./script/cibuild"
gemfile: "this/does/not/exist"
cache: bundler
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4"
