mod 'boxen',  '0.0.25', :github_tarball => 'boxen/puppet-boxen'
mod 'osx',    '0.0.1',  :github_tarball => 'boxen/puppet-osx'
mod 'stdlib', '3.0.0',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
